### ISSUE TITLE
UI issue ,need help on this

### ISSUE THREAD

**Issue by GRMK11** [Lissy93/sentiment-analysis#5] opened 2019-08-27 09:43 UTC

**Comment by lissy93** [comment] 2019-08-27 15:08
Closing this issue, as no description provided. Going forwards, please provide detailed steps of the issue, including 
- Actual Output
- Expected Output
- Steps to Reproduce (and optionally, but preferably a strip down repo or fiddle showing the issue)
---

Hi Rudra,
It looks like you actually opened this issue, with a question specific to this [Lissy93/twitter-sentiment-visualisation](https://github.com/Lissy93/twitter-sentiment-visualisation), then later edited it _(maybe once you'd realised it related to one of my other repositories)_. Not a problem - **I've replied to your original issue here: [#34](https://github.com/Lissy93/twitter-sentiment-visualisation/issues/34)** 
Hope that helps, 
Alicia :rocket:

**Closed as completed by lissy93** 2019-08-27 15:08 UTC
